### ISSUE TITLE
Wrong improvement message trailing comma in `CanonicalAnnotationSyntax` rule

### ISSUE THREAD

**Issue by dirkvbok** [PicnicSupermarket/error-prone-support#1114]
### Describe the bug

The `CanonicalAnnotationSyntax` rule provides a wrong improvement message when there is a trailing comma on a list with > 1 elements.

- [x] I have verified that the issue is reproducible against the latest version
      of the project.
- [x] I have searched through existing issues to verify that this issue is not
      already known.

### Minimal Reproducible Example

```java
@Import({
  ClassA.class,
  ClassB.class,
})
public final class ExampleConfig {}
```

<details>
<summary>Logs</summary>

```sh
[WARNING] /Users/dirkvanbokkem/Repositories/picnic-dwh-query-cache/dwh-query-cache/dwh-query-cache-web/src/main/java/tech/picnic/dwhquerycache/web/ExampleConfig.java:[5,1] [CanonicalAnnotationSyntax] Omit redundant syntax from annotation declarations
    (see https://error-prone.picnic.tech/bugpatterns/CanonicalAnnotationSyntax)
  Did you mean '@Import({'?
```
</details>

### Expected behavior

IIUC the `CanonicalAnnotationSyntax` rule checks multiple things, including the following 2:
1. if it's a single element in the list, remove the curly braces and put on single line
2. if there's a trailing comma, remove it

It's about 2., so the correct message would have been:
```
  Did you mean 'ClassB.class'?
```

### Setup

- Operating system: `MacOS Sonoma 14.4`
- Java version: `21.0.2`
- Error Prone version: `2.25.0`
- Error Prone Support version: `0.15.0`

### Additional context

In case of only a single element, the improvement message is correct because it fits on one line directly so it can show both the curly braces and the trailing comma removals.

```java
@Import({
  ClassA.class,
})
public final class ExampleConfig {}
```

<details>
<summary>Logs</summary>

```sh
[WARNING] /Users/dirkvanbokkem/Repositories/picnic-dwh-query-cache/dwh-query-cache/dwh-query-cache-web/src/main/java/tech/picnic/dwhquerycache/web/ExampleConfig.java:[5,1] [CanonicalAnnotationSyntax] Omit redundant syntax from annotation declarations
    (see https://error-prone.picnic.tech/bugpatterns/CanonicalAnnotationSyntax)
  Did you mean '@Import(ClassA.class)'?
```
</details>

**Comment by Stephan202** [comment]
Thanks for the report @dirkvbok! To be sure: this is only about the diagnostics message; when asking Error Prone to apply the patch the result is correct, right?

The issue observed here is due to us generating the fix by [replacing the full attribute](https://github.com/PicnicSupermarket/error-prone-support/blob/769779cf219d719f70dd35d47cf2e2e836e6da94/error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CanonicalAnnotationSyntax.java#L123-L125), in combination with the fact that Error Prone [only renders the first "modified" line](https://github.com/google/error-prone/blob/48ec7d90681c60dee50c0f4e46f18513a5c05166/check_api/src/main/java/com/google/errorprone/fixes/AppliedFix.java#L93-L98) when generating the diagnostics message.

Improving this inside `CanonicalAnnotationSyntax` would make the code quite a bit more complex, and it wouldn't represent a generic solution to the problem. So ideally this is improved inside Error Prone.
