### ISSUE TITLE
Document how to apply Refaster suggestions

### ISSUE THREAD

**Issue by lukelukes** [PicnicSupermarket/error-prone-support#598]
### Problem

I couldn't find any documentation on how to apply the Refaster suggestions. The suggestions coming from Errorprone are applied as expected, but the Refaster ones don't and it is not obvious how to apply them. (Does it require your fork of Errorprone?)

**Comment by Stephan202** [comment]
Ah, this is good feedback. I'll have to check, but I suspect that what's documented won't work for Maven either :sweat_smile:.

I just ran [this test](https://github.com/PicnicSupermarket/error-prone-support/blob/b344d4640ce534150858e7329ea28b9e551ccd61/refaster-runner/src/test/java/tech/picnic/errorprone/refaster/runner/RefasterTest.java#L240-L266) in IDEA with a debugger and set a breakpoint on [this lambda](https://github.com/PicnicSupermarket/error-prone-support/blob/b344d4640ce534150858e7329ea28b9e551ccd61/refaster-runner/src/main/java/tech/picnic/errorprone/refaster/runner/Refaster.java#L218). The names against which it matches for [this Refaster rule collection](https://github.com/PicnicSupermarket/error-prone-support/blob/b344d4640ce534150858e7329ea28b9e551ccd61/refaster-runner/src/test/java/tech/picnic/errorprone/refaster/runner/FooRules.java) are:
- `FooRules$ExtraGrouping$StringOfSizeTwoRule`
- `FooRules$ExtraGrouping$StringOfSizeThreeRule`
- `FooRules$StringOfSizeOneRule`
- `FooRules$StringOfSizeZeroRule`
- `FooRules$StringOfSizeZeroVerboseRule`

So I think the documentation should be updated to use `\$`instead of `\.` as a type separator. I'll test this on the command line and push a fix to the [website branch](https://github.com/PicnicSupermarket/error-prone-support/compare/master...website) once validated. Tnx for the report!

**Comment by Stephan202** [comment]
Alright, I tested it with Maven and found that (a) the inner parens were unnecessary (for the single-rule exclusion case) and (b) a `.*` suffix was missing. The website is now updated. Thanks again for reporting!

If the new documentation works for you as well I'll close the issue :)

**Comment by originalrusyn** [comment]
Hi @Stephan202 ,
Could you please suggest how to  configure Refaster to apply only specific rules?
I've tried to do it with
``` "-XepPatchChecks:Refaster:OptionalOrElseThrow", "-XepPatchLocation:IN_PLACE" ```
flags but it seems doesn't work

**Comment by Stephan202** [comment]
Hey @originalrusyn! Try with e.g. `"-XepOpt:Refaster:NamePattern=.*OptionalOrElseThrow"` :)

**Comment by originalrusyn** [comment]
@Stephan202 
Thanks,
It works for:
``` 
"-XepPatchChecks:Refaster", "-XepPatchLocation:IN_PLACE", "-XepOpt:Refaster:NamePattern=(OptionalRules.OptionalOrElseThrow|TimeRules.UtcConstant)"
```
So, I can only use regex like that to apply multiply Refaster rules in the same time?
And is it possible to configure Refaster to report about other possible refactoring (which isn't configured to refactor automatically)  it found in code  in the same time?

**Comment by Stephan202** [comment]
Happy to hear it works!

> So, I can only use regex like that to apply multiply Refaster rules at the same time?

For now the `-XepOpt:Refaster:NamePattern` regex option is indeed the only way to control what gets applied, indeed. In the context of #655 we'll look at alternatives, but I can't give a timeline for that right now.

> And is it possible to configure Refaster to report about other possible refactoring (which isn't configured to refactor automatically) it found in code at the same time?

Ah you mean to use `-XepPatchLocation:IN_PLACE` and at the same time see warnings about other Refaster rule matches? I don't think so, because patching is handled by Error Prone based on what a bug checker (in this case `Refaster`) reports, without the bug checker being aware of this. I guess a workaround could be to run the compilation twice, with different configurations. (Generally, patching is only done on-demand, while warnings are more relevant during regular builds. So perhaps a second compilation round is an acceptable price to pay.)

**Comment by lukelukes** [comment]
This is no longer an issue, thanks for the help.
