### ISSUE TITLE
Document the minimum version of errorprone required

### ISSUE THREAD

**Issue by chrismgrayftsinc** [PicnicSupermarket/error-prone-support#724]
### Problem

I was attempting to run the latest version of the rules using the version of errorprone built in to bazel 5.2.1.  This failed because it appears the latest version only works with versions of errorprone > 2.20.0 (or so).  I was not able to find any documentation of that, but there are some closed issues where people had similar problems.  It may make sense to have a compatibility matrix or something prominent in the documentation.

**Comment by Stephan202** [comment]
Hey @chrismgrayftsinc! Great idea; I'll leave this issue open as a reminder that we should add such a table. (Bit swamped at the moment, so it may take a bit. And I'll check whether this can be automated :sweat_smile:.)

Tnx for trying Error Prone Support!

**Comment by Stephan202** [comment]
Due to the way in which Refaster rules are serialized, _most_ of the time a version of Error Prone Support is only compatible with the version of Error Prone against which it is built. For `BugChecker`s there may be a larger range of compatible versions.

Just dropping here a small script that lists the version of Error Prone against which each Error Prone Support was built. To be generalized later.
```
$ git tag --list | grep -oP '(?<=^v).*' | sort -h | while read t; do echo -e "${t}\t$(git show "v${t}":pom.xml | grep -oP '(?<=<version.error-prone-orig>).+(?=</version.error-prone-orig>)')"; done
0.1.0	2.14.0
0.2.0	2.14.0
0.3.0	2.15.0
0.4.0	2.15.0
0.5.0	2.16
0.6.0	2.16
0.7.0	2.17.0
0.8.0	2.18.0
0.9.0	2.18.0
0.10.0	2.18.0
0.11.0	2.19.1
0.11.1	2.19.1
0.12.0	2.20.0
```

**Comment by Stephan202** [comment]
Hey @chrismgrayftsinc! It's been a while, but the compatibility information is now [published on the website](https://error-prone.picnic.tech/compatibility/). If you're interested in the details, see #938.
